2025-04-17 14:37:34 - candytest - "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:52" - request_by_step - INFO - 测试步骤[step_01]开始执行

2025-04-17 14:37:34 - candytest - "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:204" - __post - INFO - 接口[新增数据]开始调用

2025-04-17 14:37:34  "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:216" -__post-[print]-  这是替换后的URL：https://uat.yeeflow.cn/openapi/v1/lists/30/1818904734567501824/items 
2025-04-17 14:37:34 - candytest - "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:234" - __post - INFO - 接口响应结果：{'Data': '1912757309619834880', 'Status': 0, 'TotalCount': 0}

2025-04-17 14:37:34  "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:243" -__post-[print]-  这是jsonpath取到的值：1912757309619834880 
2025-04-17 14:37:34  "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:245" -__post-[print]-  这是tmp_variables结果: {'id': '1912757309619834880'} 
2025-04-17 14:37:34 - candytest - "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:248" - __post - INFO - 接口[新增数据]调用完成

2025-04-17 14:37:34  "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:249" -__post-[print]-  断言结果：测试用例执行通过 
2025-04-17 14:37:34 - candytest - "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:54" - request_by_step - INFO - ~~~测试步骤[step_01]执行结束~~~

2025-04-17 14:37:34 - global_except_hook - "D:\Tools\PyCharm\YeeAPITestProject\venv\lib\site-packages\nb_log\global_except_hook.py:14" - global_except_hook - ERROR - Unhandled exception:
Traceback (most recent call last):
  File "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py", line 591, in <module>
    result = r.request_by_step(case_info)
  File "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py", line 55, in request_by_step
    if result['code'] != 0:
TypeError: 'NoneType' object is not subscriptable

2025-04-17 14:44:43 - candytest - "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:63" - request_by_step - INFO - 测试步骤[step_01]开始执行

2025-04-17 14:44:43 - candytest - "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:224" - __post - INFO - 接口[新增数据]开始调用

2025-04-17 14:44:43  "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:236" -__post-[print]-  这是替换后的URL：https://uat.yeeflow.cn/openapi/v1/lists/30/1818904734567501824/items 
2025-04-17 14:44:43 - candytest - "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:254" - __post - INFO - 接口响应结果：{'Data': '1912759109051748353', 'Status': 0, 'TotalCount': 0}

2025-04-17 14:44:43  "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:263" -__post-[print]-  这是jsonpath取到的值：1912759109051748353 
2025-04-17 14:44:43  "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:265" -__post-[print]-  这是tmp_variables结果: {'id': '1912759109051748353'} 
2025-04-17 14:44:43 - candytest - "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:268" - __post - INFO - 接口[新增数据]调用完成

2025-04-17 14:44:43  "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:269" -__post-[print]-  断言结果：测试用例执行通过 
2025-04-17 14:44:43 - candytest - "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:73" - request_by_step - ERROR - 测试步骤[step_01]执行失败，因为返回结果为 None

2025-04-17 14:44:43  "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:611" -<module>-[print]-  {'code': 3, 'message': '未知错误导致返回结果为 None', 'check_result': False} 
2025-04-17 14:44:43  "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:612" -<module>-[print]-  False 
2025-04-17 14:49:43 - candytest - "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:63" - request_by_step - INFO - 测试步骤[step_01]开始执行

2025-04-17 14:49:43 - candytest - "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:223" - __post - INFO - 接口[新增数据]开始调用

2025-04-17 14:49:43  "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:235" -__post-[print]-  这是替换后的URL：https://uat.yeeflow.cn/openapi/v1/lists/30/1818904734567501824/items 
2025-04-17 14:49:43 - candytest - "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:253" - __post - INFO - 接口响应结果：{'Data': '1912760367435223041', 'Status': 0, 'TotalCount': 0}

2025-04-17 14:49:43  "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:262" -__post-[print]-  这是jsonpath取到的值：1912760367435223041 
2025-04-17 14:49:43  "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:264" -__post-[print]-  这是tmp_variables结果: {'id': '1912760367435223041'} 
2025-04-17 14:49:43 - candytest - "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:267" - __post - INFO - 接口[新增数据]调用完成

2025-04-17 14:49:43  "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:268" -__post-[print]-  断言结果：测试用例执行通过 
2025-04-17 14:49:43 - candytest - "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:72" - request_by_step - ERROR - 测试步骤[step_01]执行失败，因为返回结果为 None

2025-04-17 14:49:43  "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:610" -<module>-[print]-  {'code': 3, 'message': '未知错误导致返回结果为 None', 'check_result': False} 
2025-04-17 14:49:43  "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:611" -<module>-[print]-  False 
2025-04-17 14:50:21 - candytest - "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:63" - request_by_step - INFO - 测试步骤[step_01]开始执行

2025-04-17 14:50:21 - candytest - "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:224" - __post - INFO - 接口[新增数据]开始调用

2025-04-17 14:50:21  "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:236" -__post-[print]-  这是替换后的URL：https://uat.yeeflow.cn/openapi/v1/lists/30/1818904734567501824/items 
2025-04-17 14:50:22 - candytest - "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:254" - __post - INFO - 接口响应结果：{'Data': '1912760528689434624', 'Status': 0, 'TotalCount': 0}

2025-04-17 14:50:22  "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:263" -__post-[print]-  这是jsonpath取到的值：1912760528689434624 
2025-04-17 14:50:22  "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:265" -__post-[print]-  这是tmp_variables结果: {'id': '1912760528689434624'} 
2025-04-17 14:50:22 - candytest - "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:268" - __post - INFO - 接口[新增数据]调用完成

2025-04-17 14:50:22  "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:269" -__post-[print]-  断言结果：测试用例执行通过 
2025-04-17 14:50:22 - candytest - "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:72" - request_by_step - ERROR - 测试步骤[step_01]执行失败，因为返回结果为 None

2025-04-17 14:50:22  "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:611" -<module>-[print]-  {'code': 3, 'message': '未知错误导致返回结果为 None', 'check_result': False} 
2025-04-17 14:50:22  "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:612" -<module>-[print]-  False 
2025-04-17 14:51:39 - candytest - "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:63" - request_by_step - INFO - 测试步骤[step_01]开始执行

2025-04-17 14:51:39 - candytest - "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:224" - __post - INFO - 接口[新增数据]开始调用

2025-04-17 14:51:39  "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:236" -__post-[print]-  这是替换后的URL：https://uat.yeeflow.cn/openapi/v1/lists/30/1818904734567501824/items 
2025-04-17 14:52:00 - candytest - "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:104" - handle_exception - ERROR - 调用接口时发生连接异常，异常原因：HTTPSConnectionPool(host='uat.yeeflow.cn', port=443): Max retries exceeded with url: /openapi/v1/lists/30/1818904734567501824/items?columnType=0 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D81CBB13A0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

2025-04-17 14:52:00 - candytest - "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:67" - request_by_step - INFO - ~~~测试步骤[step_01]执行结束~~~

2025-04-17 14:52:00  "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:617" -<module>-[print]-  {'code': 3, 'message': "调用接口[新增数据]时调用接口时发生连接异常，异常原因：HTTPSConnectionPool(host='uat.yeeflow.cn', port=443): Max retries exceeded with url: /openapi/v1/lists/30/1818904734567501824/items?columnType=0 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D81CBB13A0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))", 'check_result': False} 
2025-04-17 14:52:00  "D:\Tools\PyCharm\YeeAPITestProject\common\requests_utils.py:618" -<module>-[print]-  False 
